# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '../ui/mainwindow.ui'
#
# Created: Wed Jun 20 14:38:31 2012
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1111, 699)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/logo.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet(_fromUtf8("QProgressBar:horizontal {\n"
"border: 1px solid gray;\n"
"border-radius: 1px;\n"
"background: white;\n"
"padding: 2px;\n"
"text-align: right;\n"
"}\n"
"QProgressBar::chunk:horizontal {\n"
"background: qlineargradient(x1: 0, y1: 0.5, x2: 1, y2: 0.5, stop: 0 white, stop: 1 #99cc00);\n"
"}"))
        self.central_widget = QtGui.QWidget(MainWindow)
        self.central_widget.setObjectName(_fromUtf8("central_widget"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.central_widget)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.stackedWidget = QtGui.QStackedWidget(self.central_widget)
        self.stackedWidget.setObjectName(_fromUtf8("stackedWidget"))
        self.page1 = QtGui.QWidget()
        self.page1.setObjectName(_fromUtf8("page1"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout(self.page1)
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.splitter = QtGui.QSplitter(self.page1)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.treeWidget = QtGui.QTreeWidget(self.splitter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.treeWidget.sizePolicy().hasHeightForWidth())
        self.treeWidget.setSizePolicy(sizePolicy)
        self.treeWidget.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.treeWidget.setStyleSheet(_fromUtf8(" QTreeView {\n"
"     show-decoration-selected: 1;\n"
" }\n"
"\n"
" QTreeView::item:hover {\n"
"     background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #e7effd, stop: 1 #cbdaf1);\n"
" }\n"
"\n"
" QTreeView::item:selected:active{\n"
"     background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #6ea1f1, stop: 1 #567dbc);\n"
" }\n"
"\n"
" QTreeView::item:selected:!active {\n"
"     background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #6b9be8, stop: 1 #577fbf);\n"
" }\n"
""))
        self.treeWidget.setFrameShadow(QtGui.QFrame.Sunken)
        self.treeWidget.setTabKeyNavigation(True)
        self.treeWidget.setAnimated(False)
        self.treeWidget.setObjectName(_fromUtf8("treeWidget"))
        self.treeWidget.headerItem().setText(0, _fromUtf8("1"))
        self.frame = QtGui.QFrame(self.splitter)
        self.frame.setFrameShape(QtGui.QFrame.Box)
        self.frame.setFrameShadow(QtGui.QFrame.Sunken)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.verticalLayout = QtGui.QVBoxLayout(self.frame)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.infoBrowser = QtGui.QTextBrowser(self.frame)
        self.infoBrowser.setFrameShape(QtGui.QFrame.Box)
        self.infoBrowser.setFrameShadow(QtGui.QFrame.Sunken)
        self.infoBrowser.setObjectName(_fromUtf8("infoBrowser"))
        self.verticalLayout.addWidget(self.infoBrowser)
        self.horizontalLayout_7.addWidget(self.splitter)
        self.stackedWidget.addWidget(self.page1)
        self.page2 = QtGui.QWidget()
        self.page2.setObjectName(_fromUtf8("page2"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.page2)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.selectedWidget = QtGui.QTreeWidget(self.page2)
        self.selectedWidget.setStyleSheet(_fromUtf8(" QTreeView {\n"
"     show-decoration-selected: 1;\n"
" }\n"
"\n"
" QTreeView::item:hover {\n"
"     background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #e7effd, stop: 1 #cbdaf1);\n"
"     border: 1px solid #bfcde4;\n"
" }\n"
"\n"
" QTreeView::item:selected {\n"
"     border: 1px solid #567dbc;\n"
" }\n"
"\n"
" QTreeView::item:selected:active{\n"
"     background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #6ea1f1, stop: 1 #567dbc);\n"
" }\n"
"\n"
" QTreeView::item:selected:!active {\n"
"     background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #6b9be8, stop: 1 #577fbf);\n"
" }"))
        self.selectedWidget.setObjectName(_fromUtf8("selectedWidget"))
        self.selectedWidget.headerItem().setText(0, _fromUtf8("1"))
        self.horizontalLayout_4.addWidget(self.selectedWidget)
        self.stackedWidget.addWidget(self.page2)
        self.page = QtGui.QWidget()
        self.page.setObjectName(_fromUtf8("page"))
        self.horizontalLayout_13 = QtGui.QHBoxLayout(self.page)
        self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.cherryView = QtGui.QTableView(self.page)
        self.cherryView.setObjectName(_fromUtf8("cherryView"))
        self.verticalLayout_5.addWidget(self.cherryView)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.lcdGroupBox = QtGui.QGroupBox(self.page)
        self.lcdGroupBox.setObjectName(_fromUtf8("lcdGroupBox"))
        self.horizontalLayout_12 = QtGui.QHBoxLayout(self.lcdGroupBox)
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.label_4 = QtGui.QLabel(self.lcdGroupBox)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_11.addWidget(self.label_4)
        self.strainsLcdNumber = QtGui.QLCDNumber(self.lcdGroupBox)
        self.strainsLcdNumber.setAutoFillBackground(False)
        self.strainsLcdNumber.setFrameShadow(QtGui.QFrame.Sunken)
        self.strainsLcdNumber.setLineWidth(1)
        self.strainsLcdNumber.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.strainsLcdNumber.setObjectName(_fromUtf8("strainsLcdNumber"))
        self.horizontalLayout_11.addWidget(self.strainsLcdNumber)
        self.label_5 = QtGui.QLabel(self.lcdGroupBox)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_11.addWidget(self.label_5)
        self.tracesLcdNumber = QtGui.QLCDNumber(self.lcdGroupBox)
        self.tracesLcdNumber.setFrameShadow(QtGui.QFrame.Sunken)
        self.tracesLcdNumber.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.tracesLcdNumber.setObjectName(_fromUtf8("tracesLcdNumber"))
        self.horizontalLayout_11.addWidget(self.tracesLcdNumber)
        self.label_6 = QtGui.QLabel(self.lcdGroupBox)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout_11.addWidget(self.label_6)
        self.dnaLcdNumber = QtGui.QLCDNumber(self.lcdGroupBox)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.dnaLcdNumber.setFont(font)
        self.dnaLcdNumber.setFrameShape(QtGui.QFrame.Box)
        self.dnaLcdNumber.setFrameShadow(QtGui.QFrame.Sunken)
        self.dnaLcdNumber.setLineWidth(1)
        self.dnaLcdNumber.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.dnaLcdNumber.setObjectName(_fromUtf8("dnaLcdNumber"))
        self.horizontalLayout_11.addWidget(self.dnaLcdNumber)
        self.horizontalLayout_12.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_10.addWidget(self.lcdGroupBox)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem)
        self.filterGroupBox = QtGui.QGroupBox(self.page)
        self.filterGroupBox.setObjectName(_fromUtf8("filterGroupBox"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.filterGroupBox)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.label = QtGui.QLabel(self.filterGroupBox)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setText(_fromUtf8(""))
        self.label.setPixmap(QtGui.QPixmap(_fromUtf8(":/view-filter-small.png")))
        self.label.setScaledContents(False)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_9.addWidget(self.label)
        self.label_2 = QtGui.QLabel(self.filterGroupBox)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_9.addWidget(self.label_2)
        self.userComboBox = QtGui.QComboBox(self.filterGroupBox)
        self.userComboBox.setObjectName(_fromUtf8("userComboBox"))
        self.horizontalLayout_9.addWidget(self.userComboBox)
        self.label_3 = QtGui.QLabel(self.filterGroupBox)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_9.addWidget(self.label_3)
        self.statusComboBox = QtGui.QComboBox(self.filterGroupBox)
        self.statusComboBox.setObjectName(_fromUtf8("statusComboBox"))
        self.horizontalLayout_9.addWidget(self.statusComboBox)
        self.verticalLayout_3.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_10.addWidget(self.filterGroupBox)
        self.verticalLayout_5.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_13.addLayout(self.verticalLayout_5)
        self.stackedWidget.addWidget(self.page)
        self.verticalLayout_4.addWidget(self.stackedWidget)
        self.widget = QtGui.QWidget(self.central_widget)
        self.widget.setObjectName(_fromUtf8("widget"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.widget)
        self.verticalLayout_2.setMargin(0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.selectGroupBox = QtGui.QGroupBox(self.widget)
        self.selectGroupBox.setObjectName(_fromUtf8("selectGroupBox"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.selectGroupBox)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.selectRadioButton = QtGui.QRadioButton(self.selectGroupBox)
        self.selectRadioButton.setObjectName(_fromUtf8("selectRadioButton"))
        self.horizontalLayout.addWidget(self.selectRadioButton)
        self.deselectRadioButton = QtGui.QRadioButton(self.selectGroupBox)
        self.deselectRadioButton.setObjectName(_fromUtf8("deselectRadioButton"))
        self.horizontalLayout.addWidget(self.deselectRadioButton)
        self.updateButton = QtGui.QPushButton(self.selectGroupBox)
        self.updateButton.setObjectName(_fromUtf8("updateButton"))
        self.horizontalLayout.addWidget(self.updateButton)
        self.horizontalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_3.addWidget(self.selectGroupBox)
        spacerItem1 = QtGui.QSpacerItem(628, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.fieldsGroupBox = QtGui.QGroupBox(self.widget)
        self.fieldsGroupBox.setObjectName(_fromUtf8("fieldsGroupBox"))
        self.horizontalLayout_8 = QtGui.QHBoxLayout(self.fieldsGroupBox)
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.itemTrackerButton = QtGui.QPushButton(self.fieldsGroupBox)
        self.itemTrackerButton.setObjectName(_fromUtf8("itemTrackerButton"))
        self.horizontalLayout_6.addWidget(self.itemTrackerButton)
        self.bionumericsButton = QtGui.QPushButton(self.fieldsGroupBox)
        self.bionumericsButton.setObjectName(_fromUtf8("bionumericsButton"))
        self.horizontalLayout_6.addWidget(self.bionumericsButton)
        self.horizontalLayout_8.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_3.addWidget(self.fieldsGroupBox)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.verticalLayout_4.addWidget(self.widget)
        MainWindow.setCentralWidget(self.central_widget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1111, 20))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.fileMenu = QtGui.QMenu(self.menubar)
        self.fileMenu.setObjectName(_fromUtf8("fileMenu"))
        self.viewMenu = QtGui.QMenu(self.menubar)
        self.viewMenu.setObjectName(_fromUtf8("viewMenu"))
        self.selectMenu = QtGui.QMenu(self.menubar)
        self.selectMenu.setObjectName(_fromUtf8("selectMenu"))
        self.helpMenu = QtGui.QMenu(self.menubar)
        self.helpMenu.setObjectName(_fromUtf8("helpMenu"))
        self.editMenu = QtGui.QMenu(self.menubar)
        self.editMenu.setObjectName(_fromUtf8("editMenu"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.mainToolBar = QtGui.QToolBar(MainWindow)
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.mainToolBar.setFont(font)
        self.mainToolBar.setMovable(True)
        self.mainToolBar.setIconSize(QtCore.QSize(24, 24))
        self.mainToolBar.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.mainToolBar.setFloatable(False)
        self.mainToolBar.setObjectName(_fromUtf8("mainToolBar"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.logDockWidget = QtGui.QDockWidget(MainWindow)
        self.logDockWidget.setFloating(False)
        self.logDockWidget.setFeatures(QtGui.QDockWidget.AllDockWidgetFeatures)
        self.logDockWidget.setObjectName(_fromUtf8("logDockWidget"))
        self.log_dock_widget_contents = QtGui.QWidget()
        self.log_dock_widget_contents.setObjectName(_fromUtf8("log_dock_widget_contents"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.log_dock_widget_contents)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.logBrowser = QtGui.QTextBrowser(self.log_dock_widget_contents)
        self.logBrowser.setObjectName(_fromUtf8("logBrowser"))
        self.horizontalLayout_5.addWidget(self.logBrowser)
        self.logDockWidget.setWidget(self.log_dock_widget_contents)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(8), self.logDockWidget)
        self.treeToolBar = QtGui.QToolBar(MainWindow)
        self.treeToolBar.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.treeToolBar.setObjectName(_fromUtf8("treeToolBar"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.treeToolBar)
        self.getSelectedToolBar = QtGui.QToolBar(MainWindow)
        self.getSelectedToolBar.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.getSelectedToolBar.setObjectName(_fromUtf8("getSelectedToolBar"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.getSelectedToolBar)
        self.exportToolBar = QtGui.QToolBar(MainWindow)
        self.exportToolBar.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.exportToolBar.setObjectName(_fromUtf8("exportToolBar"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.exportToolBar)
        self.actionClose = QtGui.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/application-exit.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/fileclose.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionClose.setIcon(icon1)
        self.actionClose.setObjectName(_fromUtf8("actionClose"))
        self.actionExpandItem = QtGui.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/view-list-tree.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/viewexpand.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionExpandItem.setIcon(icon2)
        self.actionExpandItem.setObjectName(_fromUtf8("actionExpandItem"))
        self.actionCollapseItem = QtGui.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/view-left-close.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/viewcollapse.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionCollapseItem.setIcon(icon3)
        self.actionCollapseItem.setObjectName(_fromUtf8("actionCollapseItem"))
        self.actionExpandAll = QtGui.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/view-fullscreen.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/viewexpandall.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionExpandAll.setIcon(icon4)
        self.actionExpandAll.setObjectName(_fromUtf8("actionExpandAll"))
        self.actionCollapseAll = QtGui.QAction(MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/view-restore.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/viewcollapseall.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionCollapseAll.setIcon(icon5)
        self.actionCollapseAll.setObjectName(_fromUtf8("actionCollapseAll"))
        self.actionSelectAll = QtGui.QAction(MainWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8(":/edit-select-all.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8(":/selectall.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionSelectAll.setIcon(icon6)
        self.actionSelectAll.setObjectName(_fromUtf8("actionSelectAll"))
        self.actionSelectNone = QtGui.QAction(MainWindow)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8(":/application-x-zerosize.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8(":/selectnone.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionSelectNone.setIcon(icon7)
        self.actionSelectNone.setObjectName(_fromUtf8("actionSelectNone"))
        self.actionSelectInvert = QtGui.QAction(MainWindow)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(_fromUtf8(":/document-encrypted.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon8.addPixmap(QtGui.QPixmap(_fromUtf8(":/selectinvert.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionSelectInvert.setIcon(icon8)
        self.actionSelectInvert.setObjectName(_fromUtf8("actionSelectInvert"))
        self.actionGetAllSelected = QtGui.QAction(MainWindow)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(_fromUtf8(":/task-complete.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionGetAllSelected.setIcon(icon9)
        self.actionGetAllSelected.setObjectName(_fromUtf8("actionGetAllSelected"))
        self.actionViewTree = QtGui.QAction(MainWindow)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(_fromUtf8(":/code-class.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionViewTree.setIcon(icon10)
        self.actionViewTree.setObjectName(_fromUtf8("actionViewTree"))
        self.actionRefresh = QtGui.QAction(MainWindow)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(_fromUtf8(":/view-refresh.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionRefresh.setIcon(icon11)
        self.actionRefresh.setObjectName(_fromUtf8("actionRefresh"))
        self.actionAbout = QtGui.QAction(MainWindow)
        self.actionAbout.setIcon(icon)
        self.actionAbout.setObjectName(_fromUtf8("actionAbout"))
        self.actionSelectInBionumerics = QtGui.QAction(MainWindow)
        self.actionSelectInBionumerics.setCheckable(True)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(_fromUtf8(":/go-jump.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSelectInBionumerics.setIcon(icon12)
        self.actionSelectInBionumerics.setObjectName(_fromUtf8("actionSelectInBionumerics"))
        self.actionClearLog = QtGui.QAction(MainWindow)
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(_fromUtf8(":/edit-clear.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionClearLog.setIcon(icon13)
        self.actionClearLog.setObjectName(_fromUtf8("actionClearLog"))
        self.actionLegend = QtGui.QAction(MainWindow)
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap(_fromUtf8(":/office-chart-pie.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionLegend.setIcon(icon14)
        self.actionLegend.setObjectName(_fromUtf8("actionLegend"))
        self.actionSelectDNA = QtGui.QAction(MainWindow)
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap(_fromUtf8(":/select-dna.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSelectDNA.setIcon(icon15)
        self.actionSelectDNA.setObjectName(_fromUtf8("actionSelectDNA"))
        self.actionSelectFrozenStock = QtGui.QAction(MainWindow)
        icon16 = QtGui.QIcon()
        icon16.addPixmap(QtGui.QPixmap(_fromUtf8(":/select-fstock.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSelectFrozenStock.setIcon(icon16)
        self.actionSelectFrozenStock.setObjectName(_fromUtf8("actionSelectFrozenStock"))
        self.actionCherryPicking = QtGui.QAction(MainWindow)
        icon17 = QtGui.QIcon()
        icon17.addPixmap(QtGui.QPixmap(_fromUtf8(":/code-function.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCherryPicking.setIcon(icon17)
        self.actionCherryPicking.setObjectName(_fromUtf8("actionCherryPicking"))
        self.actionExportTraceList = QtGui.QAction(MainWindow)
        icon18 = QtGui.QIcon()
        icon18.addPixmap(QtGui.QPixmap(_fromUtf8(":/document-export.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionExportTraceList.setIcon(icon18)
        self.actionExportTraceList.setObjectName(_fromUtf8("actionExportTraceList"))
        self.actionExportDNAList = QtGui.QAction(MainWindow)
        self.actionExportDNAList.setIcon(icon18)
        self.actionExportDNAList.setObjectName(_fromUtf8("actionExportDNAList"))
        self.fileMenu.addAction(self.actionExportDNAList)
        self.fileMenu.addAction(self.actionExportTraceList)
        self.fileMenu.addSeparator()
        self.fileMenu.addAction(self.actionClose)
        self.viewMenu.addAction(self.actionRefresh)
        self.viewMenu.addSeparator()
        self.viewMenu.addAction(self.actionGetAllSelected)
        self.viewMenu.addAction(self.actionViewTree)
        self.viewMenu.addAction(self.actionCherryPicking)
        self.viewMenu.addSeparator()
        self.viewMenu.addAction(self.actionExpandItem)
        self.viewMenu.addAction(self.actionCollapseItem)
        self.viewMenu.addAction(self.actionExpandAll)
        self.viewMenu.addAction(self.actionCollapseAll)
        self.viewMenu.addSeparator()
        self.selectMenu.addAction(self.actionSelectAll)
        self.selectMenu.addAction(self.actionSelectNone)
        self.selectMenu.addAction(self.actionSelectInvert)
        self.selectMenu.addSeparator()
        self.selectMenu.addAction(self.actionSelectDNA)
        self.selectMenu.addAction(self.actionSelectFrozenStock)
        self.selectMenu.addSeparator()
        self.selectMenu.addAction(self.actionSelectInBionumerics)
        self.helpMenu.addAction(self.actionLegend)
        self.helpMenu.addAction(self.actionAbout)
        self.editMenu.addAction(self.actionClearLog)
        self.menubar.addAction(self.fileMenu.menuAction())
        self.menubar.addAction(self.editMenu.menuAction())
        self.menubar.addAction(self.viewMenu.menuAction())
        self.menubar.addAction(self.selectMenu.menuAction())
        self.menubar.addAction(self.helpMenu.menuAction())
        self.mainToolBar.addAction(self.actionGetAllSelected)
        self.mainToolBar.addAction(self.actionViewTree)
        self.mainToolBar.addAction(self.actionCherryPicking)
        self.mainToolBar.addSeparator()
        self.mainToolBar.addAction(self.actionRefresh)
        self.mainToolBar.addAction(self.actionSelectAll)
        self.mainToolBar.addAction(self.actionSelectInvert)
        self.mainToolBar.addAction(self.actionSelectNone)
        self.mainToolBar.addAction(self.actionSelectDNA)
        self.mainToolBar.addAction(self.actionSelectFrozenStock)
        self.treeToolBar.addAction(self.actionExpandItem)
        self.treeToolBar.addAction(self.actionCollapseItem)
        self.treeToolBar.addAction(self.actionExpandAll)
        self.treeToolBar.addAction(self.actionCollapseAll)
        self.getSelectedToolBar.addAction(self.actionSelectInBionumerics)
        self.exportToolBar.addAction(self.actionExportTraceList)
        self.exportToolBar.addAction(self.actionExportDNAList)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "IT Query", None, QtGui.QApplication.UnicodeUTF8))
        self.lcdGroupBox.setTitle(QtGui.QApplication.translate("MainWindow", "Selection", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "Strains", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("MainWindow", "Traces", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("MainWindow", "DNA", None, QtGui.QApplication.UnicodeUTF8))
        self.filterGroupBox.setTitle(QtGui.QApplication.translate("MainWindow", "Filter", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "Username", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "Status", None, QtGui.QApplication.UnicodeUTF8))
        self.selectGroupBox.setTitle(QtGui.QApplication.translate("MainWindow", "ItemTracker Selection", None, QtGui.QApplication.UnicodeUTF8))
        self.selectRadioButton.setText(QtGui.QApplication.translate("MainWindow", "Select", None, QtGui.QApplication.UnicodeUTF8))
        self.deselectRadioButton.setText(QtGui.QApplication.translate("MainWindow", "Deselect", None, QtGui.QApplication.UnicodeUTF8))
        self.updateButton.setText(QtGui.QApplication.translate("MainWindow", "Update", None, QtGui.QApplication.UnicodeUTF8))
        self.fieldsGroupBox.setTitle(QtGui.QApplication.translate("MainWindow", "Select Displayed Fields", None, QtGui.QApplication.UnicodeUTF8))
        self.itemTrackerButton.setText(QtGui.QApplication.translate("MainWindow", "ItemTracker", None, QtGui.QApplication.UnicodeUTF8))
        self.bionumericsButton.setText(QtGui.QApplication.translate("MainWindow", "Bionumerics", None, QtGui.QApplication.UnicodeUTF8))
        self.fileMenu.setTitle(QtGui.QApplication.translate("MainWindow", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.viewMenu.setTitle(QtGui.QApplication.translate("MainWindow", "View", None, QtGui.QApplication.UnicodeUTF8))
        self.selectMenu.setTitle(QtGui.QApplication.translate("MainWindow", "Select", None, QtGui.QApplication.UnicodeUTF8))
        self.helpMenu.setTitle(QtGui.QApplication.translate("MainWindow", "Help", None, QtGui.QApplication.UnicodeUTF8))
        self.editMenu.setTitle(QtGui.QApplication.translate("MainWindow", "Edit", None, QtGui.QApplication.UnicodeUTF8))
        self.mainToolBar.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Main Toolbar", None, QtGui.QApplication.UnicodeUTF8))
        self.logDockWidget.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Log", None, QtGui.QApplication.UnicodeUTF8))
        self.treeToolBar.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Tree Actions Toolbar", None, QtGui.QApplication.UnicodeUTF8))
        self.getSelectedToolBar.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Get Selected Toolbar", None, QtGui.QApplication.UnicodeUTF8))
        self.exportToolBar.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Export Toolbar", None, QtGui.QApplication.UnicodeUTF8))
        self.actionClose.setText(QtGui.QApplication.translate("MainWindow", "Close", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExpandItem.setText(QtGui.QApplication.translate("MainWindow", "Expand Item", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCollapseItem.setText(QtGui.QApplication.translate("MainWindow", "Collapse Item", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExpandAll.setText(QtGui.QApplication.translate("MainWindow", "Expand All", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCollapseAll.setText(QtGui.QApplication.translate("MainWindow", "Collapse All", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSelectAll.setText(QtGui.QApplication.translate("MainWindow", "Select All", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSelectAll.setToolTip(QtGui.QApplication.translate("MainWindow", "Select all", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSelectNone.setText(QtGui.QApplication.translate("MainWindow", "Select None", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSelectNone.setToolTip(QtGui.QApplication.translate("MainWindow", "Select none", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSelectInvert.setText(QtGui.QApplication.translate("MainWindow", "Select Invert", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSelectInvert.setToolTip(QtGui.QApplication.translate("MainWindow", "Invert selection", None, QtGui.QApplication.UnicodeUTF8))
        self.actionGetAllSelected.setText(QtGui.QApplication.translate("MainWindow", "Get All Selected", None, QtGui.QApplication.UnicodeUTF8))
        self.actionGetAllSelected.setToolTip(QtGui.QApplication.translate("MainWindow", "Get all Selected from ItemTracker", None, QtGui.QApplication.UnicodeUTF8))
        self.actionViewTree.setText(QtGui.QApplication.translate("MainWindow", "View Tree", None, QtGui.QApplication.UnicodeUTF8))
        self.actionViewTree.setToolTip(QtGui.QApplication.translate("MainWindow", "View Tree", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRefresh.setText(QtGui.QApplication.translate("MainWindow", "Refresh", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRefresh.setToolTip(QtGui.QApplication.translate("MainWindow", "Refresh", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbout.setText(QtGui.QApplication.translate("MainWindow", "About", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSelectInBionumerics.setText(QtGui.QApplication.translate("MainWindow", "Select In Bionumerics", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSelectInBionumerics.setToolTip(QtGui.QApplication.translate("MainWindow", "Select in Bionumerics", None, QtGui.QApplication.UnicodeUTF8))
        self.actionClearLog.setText(QtGui.QApplication.translate("MainWindow", "Clear Log", None, QtGui.QApplication.UnicodeUTF8))
        self.actionLegend.setText(QtGui.QApplication.translate("MainWindow", "Legend", None, QtGui.QApplication.UnicodeUTF8))
        self.actionLegend.setToolTip(QtGui.QApplication.translate("MainWindow", "Color Legend", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSelectDNA.setText(QtGui.QApplication.translate("MainWindow", "Select DNA", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSelectDNA.setToolTip(QtGui.QApplication.translate("MainWindow", "Select DNA", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSelectFrozenStock.setText(QtGui.QApplication.translate("MainWindow", "Select Frozen Stock", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSelectFrozenStock.setToolTip(QtGui.QApplication.translate("MainWindow", "Select Frozen Stock", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCherryPicking.setText(QtGui.QApplication.translate("MainWindow", "Cherry Picking", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExportTraceList.setText(QtGui.QApplication.translate("MainWindow", "Export Trace List", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExportTraceList.setToolTip(QtGui.QApplication.translate("MainWindow", "Export Trace List", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExportDNAList.setText(QtGui.QApplication.translate("MainWindow", "Export DNA List", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExportDNAList.setToolTip(QtGui.QApplication.translate("MainWindow", "Export DNA List", None, QtGui.QApplication.UnicodeUTF8))

import resources_rc
